import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ChallengeCard, LogoMark, PartnershipCard, ProposalCard, PublicHeader } from "@/components/JanSamadhanUI";
import { trpc } from "@/lib/trpc";
import { ArrowDownRight, ArrowRight, Building2, CheckCircle2, CircleDot, Lightbulb, MapPin, ShieldCheck, Sparkles, University, Users2 } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function Home() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const feed = trpc.feed.get.useQuery();
  const onReport = () => setLocation(user ? "/challenges/new" : "/auth/sign-up?role=citizen");

  return <div className="min-h-screen overflow-hidden">
    <PublicHeader onReport={onReport} />
    <main>
      <section className="relative border-b border-[#dfe5e4] bg-[#edf4f1]">
        <div className="absolute inset-y-0 right-0 hidden w-[42%] bg-[#dbe9e3] lg:block" style={{ clipPath: "polygon(24% 0, 100% 0, 100% 100%, 0 100%)" }} />
        <div className="container relative grid min-h-[590px] items-center gap-12 py-16 lg:grid-cols-[1.07fr_.93fr] lg:py-20">
          <div className="reveal max-w-2xl">
            <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#c9ddd3] bg-white/75 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-[#286546]"><Sparkles className="h-3.5 w-3.5" /> A civic collaboration portal</div>
            <h1 className="display-serif max-w-xl text-5xl font-semibold leading-[1.04] tracking-tight text-[#173b72] sm:text-6xl lg:text-[5.2rem]">Local voices.<br /><span className="text-[#2d8b62]">Shared solutions.</span></h1>
            <p className="mt-7 max-w-xl text-base leading-8 text-[#536273] sm:text-lg">JanSamadhan brings citizens, universities, and industry partners together to move local challenges from a report to a practical, supported solution.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={onReport} size="lg" className="h-12 bg-[#2d8b62] px-6 text-white shadow-[0_10px_25px_rgba(45,139,98,.22)] hover:bg-[#226e4d]">Report a local challenge <ArrowRight /></Button><a href="#discover"><Button variant="outline" size="lg" className="h-12 border-[#b9ccc5] bg-white/50 px-6 text-[#173b72]">Explore what’s moving <ArrowDownRight /></Button></a></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-[#667582]"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#2d8b62]" /> Built for mobile-first participation</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#2d8b62]" /> Open ideas, grounded action</span></div>
          </div>
          <div className="relative reveal reveal-delay-1 lg:pl-10">
            <div className="relative mx-auto max-w-md rounded-[2rem] border border-white/70 bg-white/75 p-5 shadow-[0_25px_75px_rgba(23,59,114,.15)] backdrop-blur-xl">
              <div className="flex items-center justify-between border-b border-[#e6ece9] pb-4"><div className="flex items-center gap-3"><LogoMark compact /><div><p className="text-sm font-bold text-[#173b72]">Movement of an idea</p><p className="text-xs text-[#7b8790]">From report to partnership</p></div></div><span className="rounded-full bg-[#e7f4eb] px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-[#2d8b62]">Live</span></div>
              <div className="relative py-5"><div className="absolute left-[21px] top-11 h-[calc(100%-80px)] w-px bg-[#cbe1d4]" />{[{ icon: MapPin, title: "A community names the need", copy: "Water access in a village cluster" }, { icon: University, title: "A university shapes the idea", copy: "A solar-powered water monitoring kit" }, { icon: Building2, title: "An industry partner backs it", copy: "Technical support + field pilot" }].map((step, i) => <div key={step.title} className="relative flex gap-4 pb-6 last:pb-0"><div className={`z-10 grid h-11 w-11 shrink-0 place-items-center rounded-2xl border-4 border-white ${i === 2 ? "bg-[#d97706]" : "bg-[#2d8b62]"} text-white shadow-sm`}><step.icon className="h-4 w-4" /></div><div className="pt-1"><p className="text-sm font-bold text-[#173b72]">{step.title}</p><p className="mt-1 text-xs leading-5 text-[#7b8790]">{step.copy}</p></div></div>)}</div>
              <div className="rounded-2xl bg-[#f3f8f5] p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#2d8b62]">What changes?</p><p className="mt-2 text-sm font-semibold leading-6 text-[#31505c]">A challenge stays visible, a proposal finds a path, and partnership turns intent into action.</p></div>
            </div>
            <div className="absolute -bottom-6 -left-2 hidden rounded-2xl border border-[#e8d7b9] bg-[#fff8ed] p-4 shadow-xl sm:block"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f3dfb7] text-[#9b5d0a]"><CircleDot className="h-4 w-4" /></span><div><p className="text-xs font-bold text-[#7d510f]">Your voice matters</p><p className="text-[11px] text-[#a87a36]">Start with one local observation</p></div></div></div>
          </div>
        </div>
      </section>

      <section className="container -mt-8 relative z-10"><div className="grid gap-3 rounded-3xl border border-[#e0e8e4] bg-white p-4 shadow-[0_18px_45px_rgba(22,45,65,.08)] sm:grid-cols-3 sm:p-5"><Stat icon={Users2} value="3 voices" label="connected in one place" color="green" /><Stat icon={Lightbulb} value="Open ideas" label="rooted in real needs" color="blue" /><Stat icon={ShieldCheck} value="Built for trust" label="clear roles, clear action" color="amber" /></div></section>

      <section id="discover" className="container scroll-mt-24 py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#2d8b62]">Discover the movement</p><h2 className="display-serif mt-3 text-4xl font-semibold tracking-tight text-[#173b72] sm:text-5xl">What people are working on</h2></div><p className="max-w-md text-sm leading-6 text-[#65717e]">Browse the latest challenges, proposals, and partnerships. Each one is a chance to contribute something useful.</p></div>
        {feed.isLoading ? <FeedSkeleton /> : feed.isError ? <ErrorPanel /> : <div className="mt-10 space-y-16"><FeedSection title="Challenges from communities" eyebrow="01 / Citizens" action="Browse all challenges" href="/dashboard#challenges"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{feed.data?.challenges.map(challenge => <ChallengeCard key={challenge.id} challenge={challenge} />)}</div></FeedSection><FeedSection title="Ideas taking shape" eyebrow="02 / Universities" action="View all proposals" href="/dashboard#proposals"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{feed.data?.proposals.map(proposal => <ProposalCard key={proposal.id} proposal={proposal} />)}</div></FeedSection><FeedSection title="Partnerships with intent" eyebrow="03 / Industry" action="See all initiatives" href="/dashboard#partnerships"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{feed.data?.partnerships.map(partnership => <PartnershipCard key={partnership.id} partnership={partnership} />)}</div></FeedSection></div>}
      </section>

      <section id="how-it-works" className="scroll-mt-24 border-y border-[#dfe5e4] bg-[#173b72] py-24 text-white"><div className="container"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8dd0ae]">How JanSamadhan works</p><h2 className="display-serif mt-4 text-4xl font-semibold leading-tight sm:text-5xl">A simple loop for meaningful progress.</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#b8c9d8]">The best solutions start by listening. JanSamadhan makes the handoff between lived experience, research, and implementation visible.</p><Button onClick={onReport} className="mt-8 bg-[#8bd0a8] text-[#123f2d] hover:bg-[#a5e2bd]">Add your voice <ArrowRight /></Button></div><div className="grid gap-4 sm:grid-cols-3">{[{ no: "01", title: "Report", copy: "Name a challenge clearly, with context from the ground.", icon: MapPin }, { no: "02", title: "Propose", copy: "Universities bring evidence, creativity, and a path forward.", icon: Lightbulb }, { no: "03", title: "Partner", copy: "Industry partners offer the support to make it real.", icon: HandshakeIcon }].map((step, i) => <div key={step.no} className="rounded-3xl border border-white/10 bg-white/[.07] p-5"><span className="text-xs font-bold text-[#8bd0a8]">{step.no}</span><step.icon className="mt-10 h-7 w-7 text-[#d8f2e2]" /><h3 className="mt-6 text-xl font-bold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[#b8c9d8]">{step.copy}</p></div>)}</div></div></div></section>
    </main>
    <footer className="bg-[#102f57] py-8 text-[#b8c9d8]"><div className="container flex flex-col justify-between gap-4 text-xs sm:flex-row sm:items-center"><LogoMark /><span>JanSamadhan · A space for practical civic collaboration</span></div></footer>
  </div>;
}

function HandshakeIcon(props: any) { return <Building2 {...props} />; }
function Stat({ icon: Icon, value, label, color }: { icon: any; value: string; label: string; color: string }) { const styles: Record<string, string> = { green: "bg-[#e8f5ec] text-[#2d8b62]", blue: "bg-[#eaf0f9] text-[#173b72]", amber: "bg-[#fff3df] text-[#a16716]" }; return <div className="flex items-center gap-3 px-2 py-2"><span className={`grid h-10 w-10 place-items-center rounded-2xl ${styles[color]}`}><Icon className="h-5 w-5" /></span><div><p className="text-sm font-extrabold text-[#173b72]">{value}</p><p className="text-xs text-[#7a8792]">{label}</p></div></div>; }
function FeedSection({ title, eyebrow, action, href, children }: { title: string; eyebrow: string; action: string; href: string; children: React.ReactNode }) { return <div><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#84909b]">{eyebrow}</p><h3 className="mt-2 text-2xl font-bold tracking-tight text-[#173b72]">{title}</h3></div><Link href={href} className="flex items-center gap-1 text-sm font-bold text-[#2d8b62] hover:text-[#173b72]">{action} <ArrowRight className="h-4 w-4" /></Link></div>{children}</div>; }
function FeedSkeleton() { return <div className="mt-10 grid gap-5 md:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-72 animate-pulse rounded-2xl bg-[#e9efec]" />)}</div>; }
function ErrorPanel() { return <Card className="mt-10 border-[#ecd9b6] bg-[#fff8ed]"><CardContent className="p-8 text-center"><p className="font-semibold text-[#7d510f]">The community feed is taking a moment to load.</p><p className="mt-2 text-sm text-[#a87a36]">Please refresh shortly to see the latest movement.</p></CardContent></Card>; }
